### ISSUE TITLE
Bug: [Rust<>Swift] 0.2.0-alpha0 cocoapod pagination broken

### ISSUE THREAD

**Issue by michaelx11** [xmtp/xmtp-ios#103]
### Describe the bug

In testing, I realized that XMTP=0.2.0-alpha0 (published from a intermediate commit of cocoapods-integration) has broken pagination parsing for extracting the cursor from the response: https://github.com/xmtp/xmtp-ios/blob/22f8783/Sources/XMTP/ApiClient.swift#L119

This means `conversations.list()` only returns the first 100 convos. Will push a fix to this but I want to historically document:

0.2.0-alpha0 has a convos bug

**Comment by michaelx11** [comment]
Fixed in: 0.2.1-alpha0 (Cocoapod release link: https://github.com/CocoaPods/Specs/commit/a8ef70286ef676ec105637a6a488ab1dffddd3b4)

**Comment by neekolas** [comment]
Does 0.2.1 go back to the bad old perf numbers?

**Comment by michaelx11** [comment]
Nope, 0.2.1-alpha0 actually showcases even better perf numbers (~4ms per conversation instead of ~11.5)

**Comment by michaelx11** [comment]
```
Simulator numbers:

0.1.3-beta0 =  Loaded 2001 conversations in 20033ms
0.2.0-alpha0 = 100 convos in ~770ms
0.2.1-alpha0 = Loaded 2001 conversations in 8598ms

iPhone 12 Pro Max numbers
0.1.3-beta0 = Loaded 2001 conversations in 23476ms
0.2.1-alpha0 = Loaded 2001 conversations in 9789ms
```

**Comment by neekolas** [comment]
Well that's good news
