### ISSUE TITLE
Bug: ConversationV2.messages() doesn't use pagination

### ISSUE THREAD

**Issue by michaelx11** [xmtp/xmtp-ios#104]
### Describe the bug

AFFECTED VERSION: 0.1.3-beta0 (from cocoapods-integration)

As mentioned in https://github.com/xmtp/xmtp-react-native/issues/34 - a React Native SDK user noticed only 100 messages are being pulled for a convo. This lines up with the code which appears to push pagination responsibilities to the consumer, but requiring them to use Date cutoffs.

https://github.com/xmtp/xmtp-ios/blob/d9463d7/Sources/XMTP/ConversationV2.swift#L107

### Expected behavior

The consumer mentioned `.messages()` without params would be expected to return all messages in the conversation. This is their perceived expected behavior.

### Resolution

Need to confirm whether or not this is still an issue on 0.2.1-alpha0

**Comment by michaelx11** [comment]
Still an issue in 0.2.1-alpha0

**Comment by michaelx11** [comment]
If we want to replicate `listInvitations()` which does pull all possible messages, we need to pass in a `nil` pagination: https://github.com/xmtp/xmtp-ios/blob/d9463d79b3d63d4a114de14fc31a21bb74ee9289/Sources/XMTP/Conversations.swift#L264

**Comment by neekolas** [comment]
@nplasterer this was fixed in https://github.com/xmtp/xmtp-android/pull/74, right?

**Comment by nplasterer** [comment]
@neekolas the fix you have linked is for `conversation.list()` only returning 100 conversations. I don't believe I've fixed or written a test for messages. This is likely still a bug unless @dmccartney fixed it with the `batchQuery `work which did land last week.

**Comment by nplasterer** [comment]
This should be fixed on iOS now.
