### ISSUE TITLE
Bug: iOSExample App Uses WalletConnect V1

### ISSUE THREAD

**Issue by neekolas** [xmtp/xmtp-ios#131]
### Describe the bug

Our iOS example app is built on top of WalletConnect V1, which has been completely shut down. This makes the example app unusable with wallet apps.

### Expected behavior

Wallet connection is handled through V2 instead of V1

**Comment by nplasterer** [comment]
I bet this is also an issue on several other of our examples like android. I'll take a task from this to do an audit on walletconnectV1 usage.

**Comment by aloksahay** [comment]
Any update on this? V2 has been out for months!

**Comment by nakajima** [comment]
Fixed by https://github.com/xmtp/xmtp-ios/pull/166.
