### ISSUE TITLE
Bug: Framework can cause app to crash due to variable data race with async access

### ISSUE THREAD

**Issue by benjaminmayo** [xmtp/xmtp-ios#159]
### Describe the bug

The internal `conversationsByTopic` property can be accessed and mutated from various threads simultaneously due to concurrency. As access to this storage is not gated by a lock or other synchronization, this can lead to malformed memory and cause unavoidable crashes when the framework accesses that property. 

See screenshot for an example of where Xcode caught the error in the debugger:
<img width="1840" alt="Screenshot 2023-09-15 at 23 44 57" src="https://github.com/xmtp/xmtp-ios/assets/713431/43db74d5-a972-479a-9725-17bb717d9e62">

### Expected behavior

The XMTP framework should not induce crashes. 

### Steps to reproduce the bug

Client code that invokes Conversations methods which internally mutate the `conversationsByTopic` storage will eventually trigger the crash. This was first observed due to app code that observed `streamAllMessages()` and then also invoked the `list()` method.

**Comment by neekolas** [comment]
Thanks for flagging this. Great catch!
