### ISSUE TITLE
Bug: Can not create XMTP client

### ISSUE THREAD

**Issue by ajay-simform** [xmtp/xmtp-ios#173]
### Describe the bug

- I used `Client.create(
                        account: privateKey,
                        options: ClientOptions(api: .init(env: .production)))` to create an XMTP client. 
- It does work most of the time but on rare occasions, it fails to create a client. Even after retrying it is not getting created.
- If I restart the app and try, it works. I can't get the error coz most of the time it is raised on the user side.
- Any help will be appreciated. 

Thanks.

### Expected behavior

It should always create a client and allow us to proceed further

### Steps to reproduce the bug

Not have any reproduction steps. It happens suddenly and stops creating an XMTP client.

**Comment by nplasterer** [comment]
👋 Hey @ajay-simform I haven't experienced this before do you mind sharing more of your code. Otherwise this repo may be a good place to look at how an iOS app might be built https://github.com/xmtp-labs/xmtp-inbox-ios or the example app in this repo.

**Comment by fabriguespe** [comment]
I've tested the XMTPiOSExample and found that the client creation works consistently. Here's the link for reference: [XMTPiOSExample](https://github.com/xmtp/xmtp-ios/tree/main/XMTPiOSExample). I'm going to close this issue, but I'd like to hear your thoughts, @ajay-simform. Do you know of any scenarios where this might not be the case? Can share relevante code?
