### ISSUE TITLE
Cocoapods version does not support x86_64 builds

### ISSUE THREAD

**Issue by alfonsocj** [xmtp/xmtp-ios#176]
### Describe the bug

👋 I'm trying to use this library through cocoapods and I see in the podspec that the `VALID_ARCHS` is set to arm64. I'm wondering if there's a reason why x86_64 is not included. This does not happen with swift package manager, as I can build for x86_64 simulators with that one. 

If I try to build for an x86 simulator I get this error:
```
could not find module 'XMTP' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator at: Release-iphonesimulator/XMTP/XMTP.swiftmodule
```

@nakajima @nplasterer, would you happen to know the reason? 

Thanks! 🙏 

### Expected behavior

XMTP works with x86_64 simulators

### Steps to reproduce the bug

Import XMTP and build for an x86_64 simulator

**Comment by neekolas** [comment]
@nakajima is the best person to answer that. They're unfortunately out on vacation. I'm not sure if it's just as simple as adding the x86 arch, or if more work would be required to actually make it compile.

Feel free to give it a try on a fork.

**Comment by nplasterer** [comment]
I think this was just an oversight on our end. We were previously doing cocoapod publishes locally which caused some issues with the M1 laptops and would break often with xcode and os updates. We recently moved cocoapod publishing to github actions which makes the builds more stable and consistent. Let me know if the latest release fixes your issues. 🙏 Feel free to reopen otherwise.

**Comment by nplasterer** [comment]
I booted this up on my intel laptop and was able to get everything running no problem so I cannot reproduce. @fabriguespe do you mind doing a little more digging on why using expos eas builds would still be broken for react native 🙏

**Comment by alfonsocj** [comment]
I would recommend removing the `VALID_ARCHS` altogether as there are no arch limitations. https://github.com/xmtp/xmtp-ios/pull/182/files#diff-e9237cf856d38a9701faf84ef515c0d8d2880b467403b12cbe0792edf2cda630R49.
Adding this to the podspec adds it to the project as well.

**Comment by nplasterer** [comment]
Good call thanks for the suggestion @alfonsocj I just removed it entirely so hopefully this will unblock any issues.

@peterferguson can you confirm if Expo EAS builds now work on the latest react native version. 🙏
