### ISSUE TITLE
Bug: Stream disconnects on App Backgrounding

### ISSUE THREAD

**Issue by fabriguespe** [xmtp/xmtp-ios#185]
**Issue:**
Streams intermittently stop receiving messages after the app is backgrounded and re-foregrounded.

**Reproduce:**
1. Initialize a stream
2. Background or the app.
3. Foreground the app.
4. No incoming messages received.

**Expected:**
Stream maintains connection or reconnects after foregrounding.

**Actual:**
Stream 'dies' silently without errors.

**Comment by nplasterer** [comment]
It seems suspicious that this is only happening on backgrounding and then reforegrounding the app. Were you able to reproduce this @fabriguespe? I think until we can move the swift SDK over to the new `subscribe2` protocol function my advice would be to detect when network or background events happen and kill the stream and then restart the stream. Long term it would be good to do what we did here in Android https://github.com/xmtp/xmtp-android/pull/131 but this is a much heavier lift as it requires changes to `libxmtp`.

**Comment by fabriguespe** [comment]
After running some tests, the `stream` fails silently after 4-10 minutes of the app being in the background.

I've implemented a solution addressing streams intermittently stopping after the app is backgrounded and re-foregrounded. The solution involves listening for specific app state notifications and managing the stream accordingly.

Here's the relevant code:

```swift
// Rest of the code ...
func startStream() {
  streamTask = Task {
	  do {
		  for try await message in conversation.streamMessages() {
			  let content: String = try message.content()
			  print("Received message: \(content)")
			  await MainActor.run {
				  messages.append(message)
			  }
		  }
	  } catch {
		  print("Error in message stream: \(error)")
	  }
     }	
}
// Rest of the code ...
.onReceive(NotificationCenter.default.publisher(for: UIApplication.willResignActiveNotification)) { in
 streamTask?.cancel()
}
.onReceive(NotificationCenter.default.publisher(for: UIApplication.willEnterForegroundNotification)) { in
  Task{
    await loadMessages()
    startStreamTask()
  }
}
```
In this code:

1. We listen for the `UIApplication.willResignActiveNotification` notification. When this notification is received, indicating the app is moving to the background, we cancel the `streamTask`, effectively stopping the stream.

2. We also listen for the `UIApplication.willEnterForegroundNotification` notification. When this notification is received, indicating the app is moving to the foreground, we create a new task that loads the messages and starts the stream again.

This approach ensures that the stream is properly managed when the app transitions between the foreground and background states, preventing it from 'dying' silently without errors.
