### ISSUE TITLE
Docs Deployment Failure

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-ios#188]
Fix doc deployment failures
https://github.com/xmtp/xmtp-ios/actions/runs/6854544238

**Comment by nplasterer** [comment]
@fabriguespe docs deployments have been failing in iOS for a long time which means the docs page is out of date. Do you mind looking into this?

**Comment by fabriguespe** [comment]
A couple of things here is how I'm publishing docs in Android https://github.com/xmtp/xmtp-android/blob/main/.github/workflows/docs.yml I know it's a lot simpler over there but figured I'd share anyways.

Another thing I find helpful when debugging github actions is to have the actions trigger on commit so you can see if they fail or pass in CI while you develop. Which would just be adding a line like this temporarily to the top of the docs deployment file https://github.com/xmtp/xmtp-android/blob/main/.github/workflows/lint.yml#L6C16-L6C16

**Comment by fabriguespe** [comment]
@nplasterer can we allow this branch to deploy https://github.com/xmtp/xmtp-ios/actions/runs/7129348303

**Comment by fabriguespe** [comment]
Fixed [PR](https://github.com/xmtp/xmtp-ios/issues/188) & [PR](https://github.com/xmtp/xmtp-ios/pull/210)
