### ISSUE TITLE
Add a way to decode a single message

### ISSUE THREAD

**Issue by nmalzieu** [xmtp/xmtp-ios#31]
In the Javascript SDK, if we have a `conversation` instance and an encoded message, we can decode it using `conversation.decodeMessage`

Can we do the same with the SWIFT SDK? It would be useful to decode incoming notifications in an iOS Notification Extension

Bonus: if we can export / import keys (like https://github.com/xmtp/xmtp-ios/issues/30) it would also be amazing to be able to export / import saved conversations! And when importing conversations, being able to decode a notification without any access to the network, because sometimes if the connection is not good we still receive a notification, and the notification extension only has so much time to decode it

**Comment by nakajima** [comment]
There is not yet a way to do this, I think it makes sense to add though. I can look at introducing it after https://github.com/xmtp/xmtp-ios/pull/26 lands.

**Comment by nmalzieu** [comment]
Thanks @nakajima ! Can't wait to have this for Converse. I think it is the only way to have "real notifications" in a native XMTP app

iOS Notification Extension are made exactly for this: decode encoded content from notifications. Background notifications that are supposed to wake up the app are not a good solution because it doesn't work if the user killed the app. Only iOS Notification Extensions work 100% of the time!

But they don't have a lot of time to do their work before being killed by the system
Since we have the encoded message in the notification, being able to decode a single message makes sense!

**Comment by nakajima** [comment]
Now that https://github.com/xmtp/xmtp-ios/pull/41 has merged, can we close sthis?

**Comment by nmalzieu** [comment]
@nakajima this is not an issue anymore to me, you can close! Thank you for all the work!
