### ISSUE TITLE
Bug: conversations.list and converations.importTopicData collision

### ISSUE THREAD

**Issue by cb-aaron** [xmtp/xmtp-ios#352]
### Describe the bug

There seems to be a collision between client.conversations.importTopicData and client.conversations.list calls where the list call only returns 164 of my 724 conversations if called around the time importTopic data is called. This happens intermittently even if I await the importTopicData response. The full list is returned if I set a 100ms delay after importTopicData resolves.

**Comment by nplasterer** [comment]
I think this should be fixed now with https://github.com/xmtp/xmtp-ios/pull/354. Let me know if you're still seeing this issue. 🙏
